-- 1. Create Profiles table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT CHECK (role IN ('user', 'admin', 'team')) DEFAULT 'user',
  department TEXT,
  last_seen_at TIMESTAMP WITH TIME ZONE,
  viewing_complaint_id BIGINT REFERENCES public.complaints(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('Asia/Karachi'::text, NOW()) NOT NULL
);

-- 2. Create Categories table
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

-- Insert initial categories
INSERT INTO categories (name) VALUES 
('Electricity'), 
('IT Support'), 
('Cleaning'), 
('Plumbing'), 
('Security');

-- 3. Create Complaints table
CREATE TABLE complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT,
  status TEXT CHECK (status IN ('Pending', 'In Progress', 'Resolved')) DEFAULT 'Pending',
  admin_note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('Asia/Karachi'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('Asia/Karachi'::text, NOW()) NOT NULL
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- 5. Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone." ON profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." ON profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." ON profiles
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Admins can update any profile." ON profiles
  FOR UPDATE USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin'
  );

-- 6. Complaints Policies
CREATE POLICY "Users can view relevant complaints." ON complaints
  FOR SELECT USING (
    auth.uid() = user_id OR 
    (SELECT role FROM profiles WHERE id = auth.uid()) IN ('admin', 'team')
  );

CREATE POLICY "Users can insert their own complaints." ON complaints
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Admins and Team can update complaints." ON complaints
  FOR UPDATE USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN ('admin', 'team')
  );

CREATE POLICY "Admins can delete complaints." ON complaints
  FOR DELETE USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin'
  );

-- 7. Categories Policies
CREATE POLICY "Categories are viewable by everyone." ON categories
  FOR SELECT USING (true);

CREATE POLICY "Admins can insert categories." ON categories
  FOR INSERT WITH CHECK (
    (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin'
  );

CREATE POLICY "Admins can delete categories." ON categories
  FOR DELETE USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin'
  );

-- 8. Trigger for profile creation on signup
-- Note: You might need to adjust this depending on how you handle signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email, role, department)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'name', 
    new.email, 
    'user',
    new.raw_user_meta_data->>'department'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 9. Storage Configuration
-- Create 'complaints' bucket
INSERT INTO storage.buckets (id, name, public) 
VALUES ('complaints', 'complaints', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
-- Allow anyone to view complaint images
CREATE POLICY "Public Access" ON storage.objects
  FOR SELECT USING (bucket_id = 'complaints');

-- Allow authenticated users to upload images
CREATE POLICY "Authenticated users can upload images" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'complaints' AND 
    auth.role() = 'authenticated'
  );


ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE profiles ADD CONSTRAINT profiles_role_check CHECK (role IN ('user', 'admin', 'team'));

-- 10. Create Comments table for discussions
CREATE TABLE public.comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_id BIGINT REFERENCES public.complaints(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  user_name TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('Asia/Karachi'::text, NOW()) NOT NULL
);

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- Enable Realtime for comments and notifications
ALTER PUBLICATION supabase_realtime ADD TABLE public.comments;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;

CREATE POLICY "Comments are viewable by relevant parties." ON public.comments
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.complaints 
      WHERE id = complaint_id 
      AND (
        user_id = auth.uid() OR 
        (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'team')
      )
    )
  );

CREATE POLICY "Relevant parties can insert comments." ON public.comments
  FOR INSERT WITH CHECK (
    auth.uid() = user_id AND
    EXISTS (
      SELECT 1 FROM public.complaints 
      WHERE id = complaint_id 
      AND (
        user_id = auth.uid() OR 
        (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'team')
      )
    )
  );

-- 11. Create Feedback/Rating table
CREATE TABLE public.feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_id BIGINT REFERENCES public.complaints(id) ON DELETE CASCADE NOT NULL UNIQUE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
  review TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('Asia/Karachi'::text, NOW()) NOT NULL
);

ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Feedback is viewable by everyone." ON public.feedback
  FOR SELECT USING (true);

CREATE POLICY "Users can insert feedback for their resolved complaints." ON public.feedback
  FOR INSERT WITH CHECK (
    auth.uid() = user_id AND
    EXISTS (
      SELECT 1 FROM public.complaints 
      WHERE id = complaint_id AND user_id = auth.uid() AND status = 'Resolved'
    )
  );

-- 12. Internal Notifications table (for basic status alerts)
CREATE TABLE public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('Asia/Karachi'::text, NOW()) NOT NULL
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- 6. Notifications Policies
CREATE POLICY "Users can view their own notifications." ON public.notifications
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "System can insert notifications." ON public.notifications
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Users can update their own notifications." ON public.notifications
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own notifications." ON public.notifications
  FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Admins and Team can insert notifications." ON public.notifications
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE profiles.id = auth.uid() 
      AND profiles.role IN ('admin', 'team')
    )
  );
-- Trigger for notifying admins on new complaint
CREATE OR REPLACE FUNCTION public.notify_admins_on_complaint()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.notifications (user_id, title, message)
  SELECT id, 'New Complaint Filed', 'A new complaint "' || NEW.title || '" has been filed.'
  FROM public.profiles
  WHERE role = 'admin';
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_complaint_created
  AFTER INSERT ON public.complaints
  FOR EACH ROW EXECUTE FUNCTION public.notify_admins_on_complaint();

-- [REMOVED] Trigger for notifying user/staff on new comment (Disabled per user request)
-- CREATE OR REPLACE FUNCTION public.notify_on_new_comment() ...

-- Fix Deletion Constraint for Presence Heartbeat
ALTER TABLE public.profiles 
DROP CONSTRAINT IF EXISTS profiles_viewing_complaint_id_fkey;

ALTER TABLE public.profiles 
ADD CONSTRAINT profiles_viewing_complaint_id_fkey 
FOREIGN KEY (viewing_complaint_id) 

-- [NEW] Function to allow admins to delete users from auth.users
-- This must be run in the Supabase SQL Editor to take effect
CREATE OR REPLACE FUNCTION delete_user_by_admin(target_user_id uuid)
RETURNS void AS $$
BEGIN
  -- Check if the current user is an admin
  IF EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND role = 'admin'
  ) THEN
    -- Delete from auth.users (cascades to public.profiles)
    DELETE FROM auth.users WHERE id = target_user_id;
  ELSE
    RAISE EXCEPTION 'Only admins can delete users';
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- [NEW] Allow public (unauthenticated) users to view only Resolved complaints titles/categories
-- This is for the Hero Page activity feed
CREATE POLICY "Public can view resolved complaint snippets" ON public.complaints
  FOR SELECT USING (status = 'Resolved');
